"""Add property_details table

Revision ID: dd659a5f8247
Revises: 
Create Date: 2025-01-29 18:22:59.409046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd659a5f8247'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_code', sa.Integer(), nullable=True),
    sa.Column('rate_buy', sa.Float(), nullable=True),
    sa.Column('rate_lease', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('unit_no', sa.String(length=50), nullable=True),
    sa.Column('wing', sa.String(length=50), nullable=True),
    sa.Column('car_parking', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_code'], ['property.property_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_details_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_details_id'))

    op.drop_table('property_details')
    # ### end Alembic commands ###
